<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.uskoag</groupId>
        <artifactId>uskoag-gservices-parent</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>uskoag-gservices-oauth</artifactId>
    <packaging>jar</packaging>

    <description>A service to simplify use of google drive docs and other services offered through oauth. Handles safe storage of oauth credentials/tokens</description>

    <dependencies>
        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>${google.api.client.ver}</version>
        </dependency>
        <dependency>
            <groupId>com.google.oauth-client</groupId>
            <artifactId>google-oauth-client-jetty</artifactId>
            <version>${google.oauth.client.jetty.ver}</version>
        </dependency>
    </dependencies>
</project>